#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : flatpak-builder
Version  : 1.0.9
Release  : 4
URL      : https://github.com/flatpak/flatpak-builder/releases/download/1.0.9/flatpak-builder-1.0.9.tar.xz
Source0  : https://github.com/flatpak/flatpak-builder/releases/download/1.0.9/flatpak-builder-1.0.9.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: flatpak-builder-bin = %{version}-%{release}
Requires: flatpak-builder-license = %{version}-%{release}
Requires: git
Requires: ostree
Requires: patch
Requires: tar
BuildRequires : flatpak
BuildRequires : gettext
BuildRequires : git
BuildRequires : libcap-dev
BuildRequires : libxslt-bin
BuildRequires : ostree
BuildRequires : patch
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libelf)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(ostree-1)
BuildRequires : pkgconfig(yaml-0.1)
BuildRequires : sed
BuildRequires : tar
BuildRequires : valgrind
BuildRequires : xmlto

%description
<p align="center">
<img src="https://github.com/flatpak/flatpak/blob/master/flatpak.png?raw=true" alt="Flatpak icon"/>
</p>

%package bin
Summary: bin components for the flatpak-builder package.
Group: Binaries
Requires: flatpak-builder-license = %{version}-%{release}

%description bin
bin components for the flatpak-builder package.


%package license
Summary: license components for the flatpak-builder package.
Group: Default

%description license
license components for the flatpak-builder package.


%prep
%setup -q -n flatpak-builder-1.0.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570749191
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static --disable-documentation
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1570749191
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/flatpak-builder
cp COPYING %{buildroot}/usr/share/package-licenses/flatpak-builder/COPYING
cp libglnx/COPYING %{buildroot}/usr/share/package-licenses/flatpak-builder/libglnx_COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/flatpak-builder

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/flatpak-builder/COPYING
/usr/share/package-licenses/flatpak-builder/libglnx_COPYING
